### ISSUE TITLE
open-stream with --correct-order flag

### ISSUE THREAD

**Issue by chelliwell** [infostellarinc/stellarcli#129]
Could I get a bit more background on this feature please. 
Our packets will have only the 8-bit CCSDS Primary Master Channel Frame Count to identify their ordering.
It looks like the --correct-order flag might help mitigate against problems, but what are the potential kinds of out-of-sequenceness that it is aiming to cater for? Where/why might things go out of sequence - between the packets' arrival at the groundstation dish and them being received by stellarcli?
Thanks.

**Comment by davidk81** [comment]
generally, message ordering is guaranteed by the infostellar pipeline unless the satellite is explicitly flagged as "out-of-order-allowed" by the user. thus, usage of `--correct-order` flag is not needed.

trying to explain this without going into too much detail, telemetry data pipeline looks something like this:

**satellite --> modem --(local/intranet)--> starpass --(cloud messaging/tcp)--> infostellar backend --(grpc/http2)--> stellarcli/stellarapi**

in this pipeline, during the stage "**(cloud messaging/tcp)**", data is not guaranteed to be delivered in the same order as it is sent by "**starpass**" (partly due to possibility of asynchronous upload to increase throughput). thus, the messages received by "**infostellar backend**" can potentially arrive with different order than it was received by the modem. 

to mitigate this, **infostellar backend** already has mechanisms to re-order the messages (using an internal id) before delivering them to **stellarcli/stellarapi**. this mechanism is enabled by default unless the satellite is explicitly flagged as "out-of-order-allowed"

**Comment by chelliwell** [comment]
Great, thanks for the info.
